export const images = {
  SpotifyLogoBaW: require('../SpotifyIcon/SpotifyLogo.png'),
  GoogleIcon: require('../Icons/GoogleIcon.png'),
  IphoneIcon: require('../Icons/IphoneIcon.png'),
  FacebookIcon: require('../Icons/FacebookIcon.png'),
  SpotifyWrittenLogo: require('../SpotifyIcon/SpotifyWrittenLogo.png'),
  CardPic: require('../Singers/JustinBieber.png'),
  SpotifyGreenLogo: require('../SpotifyIcon/SpotifyGreenLogo.png'),
  PlayGreenLogo: require('../SpotifyIcon/PlayGreenLogo.png'),
  JB: require('../SongList/JB.jpg'),
  LoopLogo: require('../MusicPlayingIcons/LoopLogo.png'),
  NextSongLogo: require('../MusicPlayingIcons/NextSongLogo.png'),
  PreviousSongLogo: require('../MusicPlayingIcons/PreviousSongLogo.png'),
  PauseLogo: require('../MusicPlayingIcons/PauseLogo.png'),
  PlayLogo: require('../MusicPlayingIcons/PlayLogo.png'),
  ShuffleLogo: require('../MusicPlayingIcons/ShuffleLogo.png'),
  DownwardsArrowLogo: require('../MusicPlayScreenIcons/ArrowDownLogo.png'),
  HeartLogo: require('../MusicPlayScreenIcons/HeartLogo.png'),
  Properties: require('../MusicPlayScreenIcons/Properties.png'),
  ShareLogo: require('../MusicPlayScreenIcons/ShareLogo.png'),
  CastLogo: require('../MusicPlayScreenIcons/CastLogo.png'),
  SongCoverPic: require('../SongCover/SongCover.jpg'),
  SongPlayLine: require('../SongPlayLine/SongPlayLine.png'),
};
